apiVersion: v2
name: allowed-registries-policy
description: A Helm chart to deploy a Kyverno ClusterPolicy for restricting external image registries.
type: application
version: 0.1.0
appVersion: "1.0.0"
